batch_size: 4
iters: 48000

train_dataset:
  type: Dataset
  dataset_root: ../datasets/seg_all
  train_path: ../datasets/seg_all/train_all.txt
  num_classes: 4
  transforms:
    - type: RandomRotation
      max_rotation: 8
    - type: Resize
      target_size: [608, 608]
      interp: 'RANDOM'
    - type: RandomBlur
      prob: 0.4
    - type: RandomHorizontalFlip
    - type: RandomDistort
      brightness_range: 0.4
      contrast_range: 0.4
      saturation_range: 0.4
    - type: Normalize
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
      # mean: [0.0, 0.0, 0.0]
      # std: [1.0, 1.0, 1.0]
  mode: train
  

val_dataset:
  type: Dataset
  dataset_root: ../datasets/seg_all
  val_path: ../datasets/seg_all/val.txt
  num_classes: 4
  transforms:
    - type: Resize
      target_size: [608, 608]
      interp: 'LINEAR'
    - type: Normalize
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
      # mean: [0.0, 0.0, 0.0]
      # std: [1.0, 1.0, 1.0]
  mode: val



lr_scheduler:
  type: PolynomialDecay
  learning_rate: 0.0005

optimizer:
  type: sgd
  momentum: 0.9
  weight_decay: 5.0e-4

model:
  type: HarDNet
  # pretrained: ../pretrained_weights/seg/hardnet.pdparams

loss:
  types:
    - type: BootstrappedCrossEntropyLoss
      min_K: 4096
      loss_th: 0.3
  coef: [1]

  






