worker_num: 4
TrainReader:
  inputs_def:
      num_max_boxes: 50
  sample_transforms:
    - Decode: {}
    # - RandomExpandHSI: {fill_value: 0}
    # - RandomCrop: {}
    - RandomFlip: {}
  batch_transforms:
    - BatchRandomResize: {target_size: [320, 352, 384, 416, 448, 480, 512, 544, 576, 608, 640, 672, 704, 736, 768], random_size: True, random_interp: True, keep_ratio: False}
    - NormalizeBox: {}
    - PadBox: {num_max_boxes: 50}
    - BboxXYXY2XYWH: {}
    - NormalizeImage: {mean: [0.485, 0.456, 0.406], std: [0.229, 0.224, 0.225], is_scale: True}
    - Permute: {}
    - Gt2YoloTarget: {anchor_masks: [[6, 7, 8], [3, 4, 5], [0, 1, 2]], anchors: [[7, 16], [18, 24], [12, 44], [32, 40], [24, 88], [52, 65], [77, 120], [129, 176], [184, 318]], downsample_ratios: [32, 16, 8]}

  batch_size: 4
  shuffle: true
  drop_last: true
  use_shared_memory: true



EvalReader:
  inputs_def:
    num_max_boxes: 50
  sample_transforms:
    - Decode: {}
    - Resize: {target_size: [608, 608], keep_ratio: False, interp: 2}
    - NormalizeImage: {mean: [0.485, 0.456, 0.406], std: [0.229, 0.224, 0.225], is_scale: True}
    - Permute: {}
  batch_size: 1