_BASE_: [
  '../datasets/pra2022_detection.yml',
  '../runtime.yml',
  '_base_/optimizer.yml',
  '_base_/yolov5_reader.yml',
]


log_iter: 20
snapshot_epoch: 1
weights: output/yolov5_m/model_final
pretrain_weights: ../pretrained_weights/det/yolov5_m_300e_coco.pdparams


architecture: YOLOv5
norm_type: sync_bn
use_ema: True
ema_decay: 0.9999
ema_decay_type: "exponential"
act: silu
find_unused_parameters: True

depth_mult: 0.67
width_mult: 0.75


YOLOv5:
  backbone: CSPDarkNet
  neck: YOLOCSPPAN
  yolo_head: YOLOv5Head
  post_process: ~

CSPDarkNet:
  arch: "P5"
  return_idx: [2, 3, 4]
  depthwise: false

YOLOCSPPAN:
  depthwise: false

YOLOv5Head:
  anchors: [[7, 16], [18, 24], [12, 44], 
            [32, 40], [24, 88], [52, 65], 
            [77, 120], [129, 176], [184, 318]]
  anchor_masks: [[0, 1, 2], [3, 4, 5], [6, 7, 8]]
  stride: [8, 16, 32]
  loss: YOLOv3Loss

YOLOv3Loss:
  ignore_thresh: 0.7
  downsample: [32, 16, 8]
  label_smooth: true
  scale_x_y: 1.05

