_BASE_: [
  '../datasets/pra2022_detection.yml',
  '../runtime.yml',
  '_base_/optimizer.yml',
  '_base_/yolov3_reader_pra.yml',
]

snapshot_epoch: 1
weights: output/yolors/model_final

architecture: YOLOv3
pretrain_weights: ../pretrained_weights/det/ppyoloe_plus_crn_s_80e_coco.pdparams
norm_type: sync_bn
use_ema: true
ema_decay: 0.9998

YOLOv3:
  backbone: CSPResNet
  neck: CustomCSPPAN
  yolo_head: YOLOv3Head
  post_process: BBoxPostProcess

CSPResNet:
  layers: [3, 6, 6, 3]
  channels: [64, 128, 256, 512, 1024]
  return_idx: [1, 2, 3]
  use_large_stem: True
  use_alpha: True
  depth_mult: 0.33
  width_mult: 0.50

CustomCSPPAN:
  out_channels: [384, 192, 96]
  stage_num: 1
  block_num: 3
  act: 'swish'
  spp: true

YOLOv3Head:
  in_channels: [384, 192, 96]
  anchors: [[7, 16], [18, 24], [12, 44], 
            [32, 40], [24, 88], [52, 65], 
            [77, 120], [129, 176], [184, 318]]
  anchor_masks: [[6, 7, 8], [3, 4, 5], [0, 1, 2]]
  loss: YOLOv3Loss
  iou_aware: true
  iou_aware_factor: 0.5

YOLOv3Loss:
  ignore_thresh: 0.7
  downsample: [32, 16, 8]
  label_smooth: true
  scale_x_y: 1.05
  iou_loss: IouLoss
  iou_aware_loss: IouAwareLoss

BBoxPostProcess:
  decode:
    name: YOLOBox
    conf_thresh: 0.005
    downsample_ratio: 32
    clip_bbox: true
    scale_x_y: 1.05
  nms:
    name: MultiClassNMS
    keep_top_k: 50
    score_threshold: 0.3
    nms_threshold: 0.3
    nms_top_k: 500