metric: COCO
num_classes: 7

TrainDataset:
  !COCODataSet
    image_dir: images
    anno_path: train_all.json
    dataset_dir: ../datasets/det_all/
    data_fields: ['image', 'gt_bbox', 'gt_class', 'is_crowd']

EvalDataset:
  !COCODataSet
    image_dir: images
    anno_path: val.json
    dataset_dir: ../datasets/det_all/

TestDataset:
  !CustomImageFolder
    sample_num: -1