batch_size: 4  # total: 4*4
iters: 24000

train_dataset:
  type: Dataset
  dataset_root: ../datasets/seg_all
  train_path: ../datasets/seg_all/train_all.txt
  num_classes: 4
  transforms:
    - type: RandomRotation
      max_rotation: 8
    - type: Resize
      target_size: [608, 608]
      interp: 'RANDOM'
    - type: RandomBlur
      prob: 0.4
    - type: RandomHorizontalFlip
    - type: RandomDistort
      brightness_range: 0.4
      contrast_range: 0.4
      saturation_range: 0.4
    - type: Normalize
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
      # mean: [0.0, 0.0, 0.0]
      # std: [1.0, 1.0, 1.0]
  mode: train
  

val_dataset:
  type: Dataset
  dataset_root: ../datasets/seg_all
  val_path: ../datasets/seg_all/val.txt
  num_classes: 4
  transforms:
    - type: Resize
      target_size: [608, 608]
      interp: 'LINEAR'
    - type: Normalize
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
      # mean: [0.0, 0.0, 0.0]
      # std: [1.0, 1.0, 1.0]
  mode: val


optimizer:
  type: sgd
  momentum: 0.9
  weight_decay: 5.0e-4

lr_scheduler:
  type: PolynomialDecay
  learning_rate: 2.0e-3
  warmup_iters: 1000
  warmup_start_lr: 1.0e-5
  end_lr: 0
  power: 0.9

# loss:
#   types:
#     - type: OhemCrossEntropyLoss
#       min_kept: 90000   # batch_size * 1024 * 512 // 16
#     - type: OhemCrossEntropyLoss
#       min_kept: 90000
#     - type: OhemCrossEntropyLoss
#       min_kept: 90000
#   coef: [1, 1, 1]

loss:
  types:
    - type: CrossEntropyLoss
      weight: [1.0, 2.0, 2.5, 1.0]
  coef: [1, 0.4]
  


# test_config:
#   aug_eval: True
#   scales: 0.5

model:
  type: PPLiteSeg
  backbone:
    type: STDC1
  arm_out_chs: [32, 64, 128]
  seg_head_inter_chs: [32, 64, 64]
  # pretrained: ../pretrained_weights/seg/pp_lightseg_stdc1.pdparams
