batch_size: 4  # total: 4*4
iters: 24000

train_dataset:
  type: Dataset
  dataset_root: ../datasets/seg_all
  train_path: ../datasets/seg_all/train_all.txt
  num_classes: 4
  transforms:
    - type: RandomRotation
      max_rotation: 8
    - type: Resize
      target_size: [608, 608]
      interp: 'RANDOM'
    - type: RandomBlur
      prob: 0.4
    - type: RandomHorizontalFlip
    - type: RandomDistort
      brightness_range: 0.4
      contrast_range: 0.4
      saturation_range: 0.4
    - type: Normalize
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
      # mean: [0.0, 0.0, 0.0]
      # std: [1.0, 1.0, 1.0]
  mode: train
  

val_dataset:
  type: Dataset
  dataset_root: ../datasets/seg_all
  val_path: ../datasets/seg_all/val.txt
  num_classes: 4
  transforms:
    - type: Resize
      target_size: [608, 608]
      interp: 'LINEAR'
    - type: Normalize
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
      # mean: [0.0, 0.0, 0.0]
      # std: [1.0, 1.0, 1.0]
  mode: val

optimizer:
  type: AdamW
  beta1: 0.9
  beta2: 0.999
  weight_decay: 0.0125

lr_scheduler:
  type: PolynomialDecay
  learning_rate: 2.0e-4
  power: 1.
  end_lr: 1.0e-6
  warmup_iters: 400
  warmup_start_lr: 1.0e-6

loss:
  types:
    - type: CrossEntropyLoss
      weight: [1.0, 2.0, 2.5, 1.0]
  coef: [1, 0.4]

model:
  type: RTFormer
  base_channels: 32
  head_channels: 64
  use_injection: [True, True]
  # pretrained: ../pretrained_weights/seg/rtformer.pdparams
