_BASE_: [
  '../datasets/pra2022_detection.yml',
  '../runtime.yml',
  '_base_/optimizer.yml',
  '_base_/yolov3_reader_pra.yml',
]

snapshot_epoch: 1
weights: output/yolov3_res18/model_final

architecture: YOLOv3
# pretrain_weights: https://paddledet.bj.bcebos.com/models/pretrained/ResNet50_vd_ssld_pretrained.pdparams
pretrain_weights: ../pretrained_weights/det/ppyolo_r18vd_coco.pdparams
norm_type: sync_bn
use_ema: true
ema_decay: 0.9998

YOLOv3:
  backbone: ResNet
  neck: PPYOLOPAN
  yolo_head: YOLOv3Head
  post_process: BBoxPostProcess


# ResNet:
#   depth: 18
#   return_idx: [1, 2, 3]
#   freeze_at: -1
#   freeze_norm: false
#   norm_decay: 0.

ResNet:
  depth: 18
  variant: d
  return_idx: [1, 2, 3]
  freeze_at: -1
  freeze_norm: false
  norm_decay: 0.


PPYOLOPAN:
  drop_block: true
  block_size: 3
  keep_prob: 0.9
  spp: true

YOLOv3Head:
  anchors: [[7, 16], [18, 24], [12, 44], 
            [32, 40], [24, 88], [52, 65], 
            [77, 120], [129, 176], [184, 318]]
  anchor_masks: [[6, 7, 8], [3, 4, 5], [0, 1, 2]]
  loss: YOLOv3Loss
  iou_aware: true
  iou_aware_factor: 0.5

YOLOv3Loss:
  ignore_thresh: 0.7
  downsample: [32, 16, 8]
  label_smooth: true
  scale_x_y: 1.05
  iou_loss: IouLoss
  iou_aware_loss: IouAwareLoss
  loss_weight: [1.0, 1.0, 1.0, 2.0, 3.0, 2.0, 2.0]

BBoxPostProcess:
  decode:
    name: YOLOBox
    conf_thresh: 0.005
    downsample_ratio: 32
    clip_bbox: true
    scale_x_y: 1.05
  # nms:
    # name: MultiClassNMS
    # keep_top_k: 50
    # score_threshold: 0.3
    # nms_threshold: 0.3
    # nms_top_k: 500
  nms:
    name: MultiClassNMS
    keep_top_k: 100
    score_threshold: 0.01
    nms_threshold: 0.45
    nms_top_k: 1000